name: Deploy
on:
  workflow_dispatch:
jobs:
  ssh-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into server via jumpbox
        run: |
          ${{ secrets.JUMP_BOX_HOST }} >> ~/.ssh/known_hosts
          ${{ secrets.SERVER_KNOWN_HOST }} >> ~/.ssh/known_hosts
          ssh -J {{ secrets.JUMP_BOX_USER }}@${{ secrets.JUMP_BOX_IP }} ${{ secrets.USER }}@${{ secrets.SERVER_IP }}
          cd satellite-imagery-labeling-tool/
          git pull
          cp -r src/* /opt/www/label/
